version: '3.8'
services:
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - DEBUG=1
      - SERVICES=sqs,dynamodb,lambda,iam,cloudwatch,logs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'